export interface AxiosRequestMeta {
  url: string
  params: string
  code: number
  message?: string
  body?: unknown
  data?: unknown
  timestamp: number
}

export interface ExternalLogPayload {
  method: string
  url: string
  status: number
  duration: number
  request: {
    headers: Record<string, string>
    query: Record<string, any>
    body: any
    timestamp: number
  }
  response: {
    headers: Record<string, string>
    body: any
    timestamp: number
  }
  // Extended fields
  userId?: string
  traceId?: string
  bffPath?: string
  source?: string
  /**
   * Дополнительные данные, специфичные для источника.
   * Для CustomLoggerInfo сюда попадают logDetails, axiosRequests и т.п.
   */
  meta?: {
    logDetails?: Array<string | Record<string, any>>
    axiosRequests?: Array<AxiosRequestMeta>
  }
}

export interface LogEntry extends ExternalLogPayload {
  id: string // UUID or increment, generated by server
}

export type WsServerMessage
  = | { type: 'LOG_ADDED', payload: LogEntry }
    | { type: 'LOGS_CLEARED' }
    | { type: 'INITIAL_STATE', payload: LogEntry[] }

export type WsClientMessage = 'CLEAR_LOGS'

export interface LogFiltersState {
  search: string
  methods: string[]
  statuses: string[]
}
