export interface ExternalLogPayload {
  method: string;
  url: string;
  status: number;
  duration: number;
  request: {
    headers: Record<string, string>;
    query: Record<string, any>;
    body: any;
    timestamp: number;
  };
  response: {
    headers: Record<string, string>;
    body: any;
    timestamp: number;
  };
}

export interface LogEntry extends ExternalLogPayload {
  id: string; // UUID or increment, generated by server
}

export type WsServerMessage = 
  | { type: 'LOG_ADDED'; payload: LogEntry }
  | { type: 'LOGS_CLEARED' }
  | { type: 'INITIAL_STATE'; payload: LogEntry[] };

export type WsClientMessage = 'CLEAR_LOGS';

export interface LogFiltersState {
  search: string;
  methods: string[];
  statuses: string[];
}
