export interface AxiosRequestMeta {
  method?: string
  url: string
  params: string
  code: number
  message?: string
  body?: unknown
  data?: unknown
  timestamp: number
}

/**
 * Нормализованный контракт, который хранится на сервере и отправляется в клиент.
 * Внешние форматы приводятся к нему трансформерами.
 */
export interface ExternalLogPayload {
  /**
   * Дискриминатор формата/происхождения. Необязателен для обратной совместимости.
   * Позволяет отличать, например, данные из CustomLogger от «сырого» формата.
   */
  format?: 'custom-logger' | 'external-log' | 'fallback'

  method: string
  url: string
  status: number
  duration: number
  request: {
    headers: Record<string, string>
    query: Record<string, unknown>
    body: unknown
    timestamp: number
  }
  response: {
    headers: Record<string, string>
    body: unknown
    timestamp: number
  }
  // Extended fields
  userId?: string
  traceId?: string
  bffPath?: string
  source?: string
  /**
   * Дополнительные данные, специфичные для источника.
   * Для CustomLoggerInfo сюда попадают logDetails, axiosRequests и т.п.
   */
  meta?: {
    logDetails?: Array<string | Record<string, unknown>>
    axiosRequests?: Array<AxiosRequestMeta>
  }
}

export interface LogEntry extends ExternalLogPayload {
  id: string // UUID or increment, generated by server
}

export type WsServerMessage
  = | { type: 'LOG_ADDED', payload: LogEntry }
    | { type: 'LOGS_CLEARED' }
    | { type: 'INITIAL_STATE', payload: LogEntry[] }

/**
 * Клиент-сайд протокол WebSocket.
 * Используем объектный union вместо «сырых» строк для расширяемости.
 */
export type WsClientMessage = { type: 'CLEAR_LOGS' }

export interface LogFiltersState {
  search: string
  exclude: string
  globalSearch: string
  methods: string[]
  statuses: string[]
}
